services:
  facturation:
    image: frederik78/facturation:latest
    container_name: facturation
    ports:
      - "8443:8443"
    volumes:
      - ./certs:/app/certs
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped